name: 'WissKI Fruity'
description: 'WissKI environment with 2D data model.'
type: 'Site'

recipes:
  - wisski_sweet

install:
  - image_effects
  - imagemagick
  - colorbox
  - viewfield
  - wisski_iip_image
  - wisski_mirador

config:
  import:
    image_effects: '*'
    imagemagick: '*'
    colorbox: '*'
    viewfield: '*'
    wisski_iip_image: '*'
    wisski_mirador: '*'

  strict: false

  actions:
    core.entity_form_display.wisski_individual.b3f2003dbc2f46de7270ab8ccc06d193.default:
      simple_config_update:
        langcode: en
        status: true
        dependencies:
          config:
            - field.field.wisski_individual.b3f2003dbc2f46de7270ab8ccc06d193.f0f948c4575671ee7e4a1d0552faf887
            - field.field.wisski_individual.b3f2003dbc2f46de7270ab8ccc06d193.f1d31b01925bc6bfd5bd447496fa3093
            - field.field.wisski_individual.b3f2003dbc2f46de7270ab8ccc06d193.f2402bfab139280c7cc8611c3b27e137
            - field.field.wisski_individual.b3f2003dbc2f46de7270ab8ccc06d193.f2af14bc7fd10e32b7af96180e00246c
            - field.field.wisski_individual.b3f2003dbc2f46de7270ab8ccc06d193.f375e8850db4bb629823575bcb711376
            - field.field.wisski_individual.b3f2003dbc2f46de7270ab8ccc06d193.f6bcc7480ca6cf11bd0aaeb6e604f906
            - field.field.wisski_individual.b3f2003dbc2f46de7270ab8ccc06d193.f6e5faa0fd62451756d1f87fdc231af9
            - field.field.wisski_individual.b3f2003dbc2f46de7270ab8ccc06d193.f6fa82a5bab11ec9b0d83c604c3e6c02
            - field.field.wisski_individual.b3f2003dbc2f46de7270ab8ccc06d193.f749796589e0365c48a5dbe69566fee5
            - field.field.wisski_individual.b3f2003dbc2f46de7270ab8ccc06d193.f8335ad7ad526f2d29ba271bfb0fb781
            - field.field.wisski_individual.b3f2003dbc2f46de7270ab8ccc06d193.f84a521dce5ba9995b2fd94bb2a643e6
            - field.field.wisski_individual.b3f2003dbc2f46de7270ab8ccc06d193.fa9ed8fdfd2e329a7128f2225e50c05e
            - field.field.wisski_individual.b3f2003dbc2f46de7270ab8ccc06d193.fb38cabd5827b4756efbdb8c5baab258
            - field.field.wisski_individual.b3f2003dbc2f46de7270ab8ccc06d193.fc21fd0a853af8117d34bacba7612950
            - field.field.wisski_individual.b3f2003dbc2f46de7270ab8ccc06d193.fc5c6012c4c52b673e20394f5cbfa04c
            - field.field.wisski_individual.b3f2003dbc2f46de7270ab8ccc06d193.fddac03d212c691d6a89a223a45638ad
            - field.field.wisski_individual.b3f2003dbc2f46de7270ab8ccc06d193.field_mirador_viewer
            - wisski_core.wisski_bundle.b3f2003dbc2f46de7270ab8ccc06d193
          module:
            - inline_entity_form
            - text
        id: wisski_individual.b3f2003dbc2f46de7270ab8ccc06d193.default
        targetEntityType: wisski_individual
        bundle: b3f2003dbc2f46de7270ab8ccc06d193
        mode: default
        content:
          f0f948c4575671ee7e4a1d0552faf887:
            type: options_select
            weight: 5
            region: content
            settings: {  }
            third_party_settings: {  }
          f1d31b01925bc6bfd5bd447496fa3093:
            type: inline_entity_form_complex
            weight: 7
            region: content
            settings:
              form_mode: default
              override_labels: false
              label_singular: ''
              label_plural: ''
              allow_new: true
              allow_existing: true
              match_operator: CONTAINS
              allow_duplicate: false
              collapsible: false
              collapsed: false
              revision: false
              removed_reference: optional
            third_party_settings: {  }
          f2af14bc7fd10e32b7af96180e00246c:
            type: inline_entity_form_complex
            weight: 9
            region: content
            settings:
              form_mode: default
              override_labels: false
              label_singular: ''
              label_plural: ''
              allow_new: true
              allow_existing: true
              match_operator: CONTAINS
              allow_duplicate: false
              collapsible: false
              collapsed: false
              revision: false
              removed_reference: optional
            third_party_settings: {  }
          f375e8850db4bb629823575bcb711376:
            type: options_select
            weight: 1
            region: content
            settings: {  }
            third_party_settings: {  }
          f6bcc7480ca6cf11bd0aaeb6e604f906:
            type: inline_entity_form_complex
            weight: 4
            region: content
            settings:
              form_mode: default
              override_labels: false
              label_singular: ''
              label_plural: ''
              allow_new: true
              allow_existing: true
              match_operator: CONTAINS
              allow_duplicate: false
              collapsible: false
              collapsed: false
              revision: false
              removed_reference: optional
            third_party_settings: {  }
          f6e5faa0fd62451756d1f87fdc231af9:
            type: string_textfield
            weight: 2
            region: content
            settings:
              size: 60
              placeholder: ''
            third_party_settings: {  }
          f6fa82a5bab11ec9b0d83c604c3e6c02:
            type: inline_entity_form_complex
            weight: 6
            region: content
            settings:
              form_mode: default
              override_labels: false
              label_singular: ''
              label_plural: ''
              allow_new: true
              allow_existing: true
              match_operator: CONTAINS
              allow_duplicate: false
              collapsible: false
              collapsed: false
              revision: false
              removed_reference: optional
            third_party_settings: {  }
          f749796589e0365c48a5dbe69566fee5:
            type: text_textarea
            weight: 19
            region: content
            settings:
              rows: 5
              placeholder: ''
            third_party_settings: {  }
          f8335ad7ad526f2d29ba271bfb0fb781:
            type: text_textarea_with_summary
            weight: 18
            region: content
            settings:
              rows: 9
              summary_rows: 3
              placeholder: ''
              show_summary: false
            third_party_settings: {  }
          fa9ed8fdfd2e329a7128f2225e50c05e:
            type: string_textfield
            weight: 3
            region: content
            settings:
              size: 60
              placeholder: ''
            third_party_settings: {  }
          fb38cabd5827b4756efbdb8c5baab258:
            type: inline_entity_form_complex
            weight: 10
            region: content
            settings:
              form_mode: default
              override_labels: false
              label_singular: ''
              label_plural: ''
              allow_new: true
              allow_existing: true
              match_operator: CONTAINS
              allow_duplicate: false
              collapsible: false
              collapsed: false
              revision: false
              removed_reference: optional
            third_party_settings: {  }
          fc21fd0a853af8117d34bacba7612950:
            type: inline_entity_form_complex
            weight: 13
            region: content
            settings:
              form_mode: default
              override_labels: false
              label_singular: ''
              label_plural: ''
              allow_new: true
              allow_existing: false
              match_operator: CONTAINS
              allow_duplicate: false
              collapsible: false
              collapsed: false
              revision: false
              removed_reference: optional
            third_party_settings: {  }
          fc5c6012c4c52b673e20394f5cbfa04c:
            type: inline_entity_form_complex
            weight: 14
            region: content
            settings:
              form_mode: default
              override_labels: false
              label_singular: ''
              label_plural: ''
              allow_new: true
              allow_existing: true
              match_operator: CONTAINS
              allow_duplicate: false
              collapsible: false
              collapsed: false
              revision: false
              removed_reference: optional
            third_party_settings: {  }
          fddac03d212c691d6a89a223a45638ad:
            type: inline_entity_form_complex
            weight: 0
            region: content
            settings:
              form_mode: default
              override_labels: false
              label_singular: ''
              label_plural: ''
              allow_new: true
              allow_existing: true
              match_operator: CONTAINS
              allow_duplicate: false
              collapsible: false
              collapsed: false
              revision: false
              removed_reference: optional
            third_party_settings: {  }
        hidden:
          created: true
          f2402bfab139280c7cc8611c3b27e137: true
          f84a521dce5ba9995b2fd94bb2a643e6: true
          field_mirador_viewer: true
          label: true
          name: true
          uid: true
    core.entity_view_display.wisski_individual.b3f2003dbc2f46de7270ab8ccc06d193.default:
      simple_config_update:
        langcode: en
        status: true
        dependencies:
          config:
            - field.field.wisski_individual.b3f2003dbc2f46de7270ab8ccc06d193.f0f948c4575671ee7e4a1d0552faf887
            - field.field.wisski_individual.b3f2003dbc2f46de7270ab8ccc06d193.f1d31b01925bc6bfd5bd447496fa3093
            - field.field.wisski_individual.b3f2003dbc2f46de7270ab8ccc06d193.f2402bfab139280c7cc8611c3b27e137
            - field.field.wisski_individual.b3f2003dbc2f46de7270ab8ccc06d193.f2af14bc7fd10e32b7af96180e00246c
            - field.field.wisski_individual.b3f2003dbc2f46de7270ab8ccc06d193.f375e8850db4bb629823575bcb711376
            - field.field.wisski_individual.b3f2003dbc2f46de7270ab8ccc06d193.f6bcc7480ca6cf11bd0aaeb6e604f906
            - field.field.wisski_individual.b3f2003dbc2f46de7270ab8ccc06d193.f6e5faa0fd62451756d1f87fdc231af9
            - field.field.wisski_individual.b3f2003dbc2f46de7270ab8ccc06d193.f6fa82a5bab11ec9b0d83c604c3e6c02
            - field.field.wisski_individual.b3f2003dbc2f46de7270ab8ccc06d193.f749796589e0365c48a5dbe69566fee5
            - field.field.wisski_individual.b3f2003dbc2f46de7270ab8ccc06d193.f8335ad7ad526f2d29ba271bfb0fb781
            - field.field.wisski_individual.b3f2003dbc2f46de7270ab8ccc06d193.f84a521dce5ba9995b2fd94bb2a643e6
            - field.field.wisski_individual.b3f2003dbc2f46de7270ab8ccc06d193.fa9ed8fdfd2e329a7128f2225e50c05e
            - field.field.wisski_individual.b3f2003dbc2f46de7270ab8ccc06d193.fb38cabd5827b4756efbdb8c5baab258
            - field.field.wisski_individual.b3f2003dbc2f46de7270ab8ccc06d193.fc21fd0a853af8117d34bacba7612950
            - field.field.wisski_individual.b3f2003dbc2f46de7270ab8ccc06d193.fc5c6012c4c52b673e20394f5cbfa04c
            - field.field.wisski_individual.b3f2003dbc2f46de7270ab8ccc06d193.fddac03d212c691d6a89a223a45638ad
            - field.field.wisski_individual.b3f2003dbc2f46de7270ab8ccc06d193.field_mirador_viewer
            - wisski_core.wisski_bundle.b3f2003dbc2f46de7270ab8ccc06d193
          module:
            - options
            - text
            - viewfield
            - wisski_adapter_sparql11_pb
        id: wisski_individual.b3f2003dbc2f46de7270ab8ccc06d193.default
        targetEntityType: wisski_individual
        bundle: b3f2003dbc2f46de7270ab8ccc06d193
        mode: default
        content:
          f0f948c4575671ee7e4a1d0552faf887:
            type: list_default
            label: above
            settings: {  }
            third_party_settings: {  }
            weight: 5
            region: content
          f1d31b01925bc6bfd5bd447496fa3093:
            type: entity_reference_entity_view
            label: above
            settings:
              view_mode: default
              link: false
            third_party_settings: {  }
            weight: 7
            region: content
          f2af14bc7fd10e32b7af96180e00246c:
            type: wisski_entity_reference_label
            label: above
            settings:
              link: true
            third_party_settings: {  }
            weight: 9
            region: content
          f375e8850db4bb629823575bcb711376:
            type: list_default
            label: above
            settings: {  }
            third_party_settings: {  }
            weight: 1
            region: content
          f6bcc7480ca6cf11bd0aaeb6e604f906:
            type: wisski_entity_reference_label
            label: above
            settings:
              link: true
            third_party_settings: {  }
            weight: 4
            region: content
          f6e5faa0fd62451756d1f87fdc231af9:
            type: string
            label: above
            settings:
              link_to_entity: false
            third_party_settings: {  }
            weight: 2
            region: content
          f6fa82a5bab11ec9b0d83c604c3e6c02:
            type: entity_reference_label
            label: above
            settings:
              link: true
            third_party_settings: {  }
            weight: 6
            region: content
          f749796589e0365c48a5dbe69566fee5:
            type: text_default
            label: above
            settings: {  }
            third_party_settings: {  }
            weight: 14
            region: content
          f8335ad7ad526f2d29ba271bfb0fb781:
            type: text_default
            label: above
            settings: {  }
            third_party_settings: {  }
            weight: 13
            region: content
          f84a521dce5ba9995b2fd94bb2a643e6:
            type: entity_reference_entity_view
            label: above
            settings:
              view_mode: default
              link: false
            third_party_settings: {  }
            weight: 8
            region: content
          fa9ed8fdfd2e329a7128f2225e50c05e:
            type: string
            label: above
            settings:
              link_to_entity: false
            third_party_settings: {  }
            weight: 3
            region: content
          fb38cabd5827b4756efbdb8c5baab258:
            type: entity_reference_entity_view
            label: above
            settings:
              view_mode: default
              link: false
            third_party_settings: {  }
            weight: 10
            region: content
          fc21fd0a853af8117d34bacba7612950:
            type: wisski_entity_reference_label
            label: above
            settings:
              link: true
            third_party_settings: {  }
            weight: 11
            region: content
          fc5c6012c4c52b673e20394f5cbfa04c:
            type: entity_reference_entity_view
            label: above
            settings:
              view_mode: default
              link: false
            third_party_settings: {  }
            weight: 12
            region: content
          field_mirador_viewer:
            type: viewfield_default
            label: above
            settings:
              view_title: hidden
              always_build_output: false
              empty_view_title: hidden
            third_party_settings: {  }
            weight: 0
            region: content
        hidden:
          bundle: true
          created: true
          f2402bfab139280c7cc8611c3b27e137: true
          fddac03d212c691d6a89a223a45638ad: true
          label: true
          name: true
          preview_image: true
          uid: true
          wisski_uri: true
    system.image:
      simple_config_update:
        toolkit: imagemagick

