name: 'WissKI Fruity'
description: 'WissKI environment with 2D data model.'
type: 'Site'

recipes:
  - wisski_sweet

install:
  - image_effects
  - imagemagick
  - colorbox
  - viewfield
  - wisski_iip_image
  - wisski_mirador

config:
  #strict: false # https://www.drupal.org/project/drupal/issues/3478332
  import:
    image_effects: '*'
    imagemagick: '*'
    colorbox: '*'
    viewfield: '*'
  actions:
    core.entity_form_display.wisski_individual.b3f2003dbc2f46de7270ab8ccc06d193.default:
      setComponents:
        -
          name: fddac03d212c691d6a89a223a45638ad
          options:
            type: inline_entity_form_complex
            weight: 0
            region: content
            settings:
              form_mode: default
              override_labels: false
              label_singular: ''
              label_plural: ''
              allow_new: true
              allow_existing: true
              match_operator: CONTAINS
              allow_duplicate: false
              collapsible: false
              collapsed: false
              revision: false
              removed_reference: optional
            third_party_settings: {  }
        -
          name: f2402bfab139280c7cc8611c3b27e137
          options:
            region: hidden
        -
          name: f84a521dce5ba9995b2fd94bb2a643e6
          options:
            region: hidden
        -
          name: field_mirador_viewer
          options:
            region: hidden
    core.entity_view_display.wisski_individual.b3f2003dbc2f46de7270ab8ccc06d193.default:
      setComponents:
        -
          name: field_mirador_viewer
          options:
            type: viewfield_default
            label: above
            settings:
              view_title: hidden
              always_build_output: false
              empty_view_title: hidden
            third_party_settings: {  }
            weight: 0
            region: content
        -
          name: f2402bfab139280c7cc8611c3b27e137
          options:
            region: hidden
        -
          name: fddac03d212c691d6a89a223a45638ad
          options:
            region: hidden
    system.image:
      simple_config_update:
        toolkit: imagemagick

