name: 'WissKI Fruity'
description: 'WissKI environment with 2D data model.'
type: 'Site'

recipes:
  - wisski_sweet

install:
  - image_effects
  - imagemagick
  - colorbox
  - wisski_iip_image
  - wisski_mirador

config:
  strict: false
  import:
    image_effects: "*"
    imagemagick: "*"
    colorbox: "*"
    wisski_iip_image: "*"
    wisski_mirador: "*"
